using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UGS.Runtime;
using UGS.Runtime.Core;
using UnityEngine;
/* Auto Generated By UGS  */
using UGS.Runtime.Core;
namespace Game
{
    public class Item : BaseSchema<ItemModel>
    {
    }
}

namespace Game
{
    public class ItemModel
    {
        public System.String id;
        public System.String name;
    }
}
public enum GlobalEnumType
{
    A = 10,
    B = 20
}
namespace UGS.Test
{
    public class Test : MonoBehaviour
    {
        public enum TestType
        {
            A = 10,
            B = 20
        } 
        void Start()
        { 

            UniGoogleSheets.Initialize(CodegenOption.Both);
            //Game.Item.List.ForEach(x =>
            //{
            //    Debug.Log(x.id + "," + x.name);
            //});




            SpreadSheetData data = new SpreadSheetData()
            {
                Meta = new Metadata("1293129321", "Game", "Item"),
                Columns = new List<Colum>()
                {
                    {
                        new Colum("hi", "int", new string[] {"a", "b"})
                    }
                }
            };

        }
    }
}
